name: Production Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run:
    runs-on: linux

    steps:
    - uses: actions/checkout@v3
    - name: Clean docker
      run: docker image prune -f
    - name: Run server
      run: docker-compose up --build -d
