version: '3.7'
services:
  nginx:
    container_name: admin-panel-stars
    build:
      context: ./admin/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always
  meta:
    container_name: supabase-meta
    image: supabase/postgres-meta:v0.59.0
    restart: unless-stopped
    environment:
      PG_META_PORT: '8080'
      PG_META_DB_HOST: 'db'
      PG_META_DB_PORT: '5432'
      PG_META_DB_NAME: 'postgres'
      PG_META_DB_USER: 'supabase_admin'
      PG_META_DB_PASSWORD: 'fuf12fuS11'